name: taproot_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dartz: ^0.10.1
  flutter_spinkit: ^5.2.1
  pinput: ^5.0.1
  google_sign_in: ^6.3.0
  country_code_picker: ^3.3.0
  # firebase_auth: ^5.5.2
  # firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  flutter_svg: ^2.0.17
  animations: ^2.0.11
  jwt_decoder: ^2.0.1
  get: ^4.7.2
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  # firebase_messaging: ^15.2.5
  webview_flutter: ^4.10.0
  # firebase_crashlytics: ^4.3.5
  gap: ^3.0.1
  lottie: ^3.3.1
  device_info_plus: ^11.3.3
  package_info_plus: ^8.3.0
  file_picker: ^10.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  url_launcher: ^6.3.1
  # cloud_firestore: ^5.6.6
  intl: "any"
  # intl: ~0.19.0


  # geolocator: ^13.0.4
  # geocoding: ^3.0.0
  dotted_border: ^3.0.1
  cached_network_image: ^3.4.1
  flutter_typeahead: ^5.2.0
  infinite_scroll_pagination: ^5.0.0
  fluttertoast: ^8.2.12
  dio_cookie_manager: ^3.2.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.4
  flutter_local_notifications: ^19.0.0
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.12.1
  screen_protector: ^1.4.2+1
  build_runner: ^2.4.15
  flutter_gen: ^5.10.0
  lucide_icons_flutter: ^2.0.3

  easy_sidemenu: ^0.6.1
  # used 0.6.1 version easy sidemenu when develop
  lucide_icons: ^0.257.0
  syncfusion_flutter_charts: ^29.1.40
  flutter_regex: ^0.0.3
  http_parser: ^4.1.2
  searchable_listview: ^2.17.3
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  file_saver: ^0.2.14
  window_size: ^0.1.0
  one_clock: ^1.0.1
  flutter_localizations_plus: ^0.2.7
  flutter_local_network_ios: ^0.0.1
  flutter_localizations:
    sdk: flutter
  pretty_qr_code: ^3.4.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    # - images/a_dot_ham.jpeg
    - assets/png/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
        - asset: assets/fonts/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter_18pt-LightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-Thin.ttf
        - asset: assets/fonts/Inter_18pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_24pt-Black.ttf
        - asset: assets/fonts/Inter_24pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Italic.ttf
        - asset: assets/fonts/Inter_24pt-Light.ttf
        - asset: assets/fonts/Inter_24pt-LightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Medium.ttf
        - asset: assets/fonts/Inter_24pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
        - asset: assets/fonts/Inter_24pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-Thin.ttf
        - asset: assets/fonts/Inter_24pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_28pt-Black.ttf
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
        

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
